### ISSUE TITLE
Static generator to create site, documentation and templates !

### ISSUE THREAD

**Issue by jgatjens** [hangarcr/gethangar#2]
Ruby:
- Jekyll (23464) starts github
- Middleman (4930)

Node:
- Supercollider + handlebars
- GitBook
- Hexo (8342)

GO:
- Hugo (8162)

**Comment by Warlord08** [comment]
Is this the final list of technologies or just a proposal?

**Comment by jgatjens** [comment]
@Warlord08 just some. nothing is final yet.
Im playing with supercollider and looks very promising !

**Comment by Warlord08** [comment]
Including the URLs - just in case someone is interested on playing a little (or have no experience, like myself)

Ruby:

    [Jekyll](https://jekyllrb.com/)
    [Middleman](https://middlemanapp.com/) 

Node:

    [Supercollider](https://github.com/crucialfelix/supercolliderjs) + handlebars
    [GitBook](https://www.gitbook.com/)
    [Hexo](https://hexo.io/) 

GO:

    [Hugo](https://gohugo.io/

**Comment by jgatjens** [comment]
:+1: Gracias !

**Comment by jrgherrera** [comment]
Take a look at this: [Jade](http://jade-lang.com/)

**Comment by jgatjens** [comment]
@jrgherrera Jade + what:question:

**Comment by jgatjens** [comment]
I like how Jekyll generate html from markdown. Really easy to update. 
It also allow me to include html and have that use the highlight tag build in jekyll.

I made an example in this branch:
https://github.com/hangarcr/gethangar/tree/feature/jekyll
